pragma solidity 0.7.3;
interface DateTimeInterface {
  function DOW_FRI (  ) external view returns ( uint256 );
  function DOW_MON (  ) external view returns ( uint256 );
  function DOW_SAT (  ) external view returns ( uint256 );
  function DOW_SUN (  ) external view returns ( uint256 );
  function DOW_THU (  ) external view returns ( uint256 );
  function DOW_TUE (  ) external view returns ( uint256 );
  function DOW_WED (  ) external view returns ( uint256 );
  function OFFSET19700101 (  ) external view returns ( int256 );
  function SECONDS_PER_DAY (  ) external view returns ( uint256 );
  function SECONDS_PER_HOUR (  ) external view returns ( uint256 );
  function SECONDS_PER_MINUTE (  ) external view returns ( uint256 );
  function _daysFromDate ( uint256 year, uint256 month, uint256 day ) external pure returns ( uint256 _days );
  function _daysToDate ( uint256 _days ) external pure returns ( uint256 year, uint256 month, uint256 day );
  function _getDaysInMonth ( uint256 year, uint256 month ) external pure returns ( uint256 daysInMonth );
  function _isLeapYear ( uint256 year ) external pure returns ( bool leapYear );
  function _now (  ) external view returns ( uint256 timestamp );
  function _nowDateTime (  ) external view returns ( uint256 year, uint256 month, uint256 day, uint256 hour, uint256 minute, uint256 second );
  function addDays ( uint256 timestamp, uint256 _days ) external pure returns ( uint256 newTimestamp );
  function addHours ( uint256 timestamp, uint256 _hours ) external pure returns ( uint256 newTimestamp );
  function addMinutes ( uint256 timestamp, uint256 _minutes ) external pure returns ( uint256 newTimestamp );
  function addMonths ( uint256 timestamp, uint256 _months ) external pure returns ( uint256 newTimestamp );
  function addSeconds ( uint256 timestamp, uint256 _seconds ) external pure returns ( uint256 newTimestamp );
  function addYears ( uint256 timestamp, uint256 _years ) external pure returns ( uint256 newTimestamp );
  function diffDays ( uint256 fromTimestamp, uint256 toTimestamp ) external pure returns ( uint256 _days );
  function diffHours ( uint256 fromTimestamp, uint256 toTimestamp ) external pure returns ( uint256 _hours );
  function diffMinutes ( uint256 fromTimestamp, uint256 toTimestamp ) external pure returns ( uint256 _minutes );
  function diffMonths ( uint256 fromTimestamp, uint256 toTimestamp ) external pure returns ( uint256 _months );
  function diffSeconds ( uint256 fromTimestamp, uint256 toTimestamp ) external pure returns ( uint256 _seconds );
  function diffYears ( uint256 fromTimestamp, uint256 toTimestamp ) external pure returns ( uint256 _years );
  function getDay ( uint256 timestamp ) external pure returns ( uint256 day );
  function getDayOfWeek ( uint256 timestamp ) external pure returns ( uint256 dayOfWeek );
  function getDaysInMonth ( uint256 timestamp ) external pure returns ( uint256 daysInMonth );
  function getHour ( uint256 timestamp ) external pure returns ( uint256 hour );
  function getMinute ( uint256 timestamp ) external pure returns ( uint256 minute );
  function getMonth ( uint256 timestamp ) external pure returns ( uint256 month );
  function getSecond ( uint256 timestamp ) external pure returns ( uint256 second );
  function getYear ( uint256 timestamp ) external pure returns ( uint256 year );
  function isLeapYear ( uint256 timestamp ) external pure returns ( bool leapYear );
  function isValidDate ( uint256 year, uint256 month, uint256 day ) external pure returns ( bool valid );
  function isValidDateTime ( uint256 year, uint256 month, uint256 day, uint256 hour, uint256 minute, uint256 second ) external pure returns ( bool valid );
  function isWeekDay ( uint256 timestamp ) external pure returns ( bool weekDay );
  function isWeekEnd ( uint256 timestamp ) external pure returns ( bool weekEnd );
  function subDays ( uint256 timestamp, uint256 _days ) external pure returns ( uint256 newTimestamp );
  function subHours ( uint256 timestamp, uint256 _hours ) external pure returns ( uint256 newTimestamp );
  function subMinutes ( uint256 timestamp, uint256 _minutes ) external pure returns ( uint256 newTimestamp );
  function subMonths ( uint256 timestamp, uint256 _months ) external pure returns ( uint256 newTimestamp );
  function subSeconds ( uint256 timestamp, uint256 _seconds ) external pure returns ( uint256 newTimestamp );
  function subYears ( uint256 timestamp, uint256 _years ) external pure returns ( uint256 newTimestamp );
  function timestampFromDate ( uint256 year, uint256 month, uint256 day ) external pure returns ( uint256 timestamp );
  function timestampFromDateTime ( uint256 year, uint256 month, uint256 day, uint256 hour, uint256 minute, uint256 second ) external pure returns ( uint256 timestamp );
  function timestampToDate ( uint256 timestamp ) external pure returns ( uint256 year, uint256 month, uint256 day );
  function timestampToDateTime ( uint256 timestamp ) external pure returns ( uint256 year, uint256 month, uint256 day, uint256 hour, uint256 minute, uint256 second );
}
